import Navbar from "@/app/components/Navbar";
import "./global.css";
import { FactProvider } from "./lib/FactContext";
import { Toaster } from "sonner";
import { AuthProvider } from "./lib/AuthContext";

export const metadata = {
  title: "Useless Facts",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main>
          <AuthProvider>
            <FactProvider>
              <Toaster
                expand
                position="top-right"
                richColors
                pauseWhenPageIsHidden
              />
              <Navbar />
              {children}
            </FactProvider>
          </AuthProvider>
        </main>
      </body>
    </html>
  );
}
