import { Toaster } from "sonner";
import "./global.css";

export const metadata = {
  title: "Useless Facts",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Toaster position="bottom-right" richColors pauseWhenPageIsHidden />

        {children}
      </body>
    </html>
  );
}
