import Navbar from "../components/Navbar";
import { FactProvider } from "../lib/FactContext";
import styles from "./FactLayout.module.css";

export const metadata = {
  title: "Home Page",
  description: "Generated by Next.js",
};

export default function FactLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <FactProvider>
      <main className={styles.container}>
        <Navbar />
        <section className={styles.content}>{children}</section>
      </main>
    </FactProvider>
  );
}
