import { Suspense } from "react";
import Navbar from "../components/Navbar";
import { FactProvider } from "../lib/FactContext";
import styles from "./FactLayout.module.css";
import Loading from "./loading";

export const metadata = {
  title: "Home Page",
  description: "Generated by Next.js",
};

export default function FactLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <FactProvider>
      {/*
  Suspense with a fallback prevents the page from being unresponsive
  during initial loading or dynamic imports, displaying a loading
  indicator until the children are ready.
*/}
      <Suspense fallback={<Loading />}>
        <main className={styles.container}>
          <Navbar />
          <section className={styles.content}>{children}</section>
        </main>
      </Suspense>
    </FactProvider>
  );
}
