import { Suspense } from "react";
import { FactProvider } from "@/utils/FactContext";

import Navbar from "../components/Navbar";
import styles from "./FactLayout.module.css";
import Loading from "./loading";

export const metadata = {
  title: "Home Page",
  description: "Generated by Next.js",
};

export default async function FactLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <FactProvider>
      {/*
  Suspense with a fallback prevents the page from being unresponsive
  during initial loading or dynamic imports, displaying a loading
  indicator until the children are ready.
*/}
      <main className={styles.container}>
        <Suspense fallback={<Loading />}>
          <Navbar />
          <section className={styles.content}>{children}</section>
        </Suspense>
      </main>
    </FactProvider>
  );
}
